---
title: "Strings and Factors"
output: github_document
---
```{r}
library(tidyverse)
library(p8105.datasets)
library(rvest)
library(httr)


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

## all plots i make will have the viridis color palette
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

## Restaurant example

What is a parsing failure?
If one of the import steps that converts data from one form to anther, and it doesn't match, R will think the data is wrong 
```{r}
api_url = "https://data.cityofnewyork.us/resource/43nn-pn8j.csv"

rest_inspections = 
  GET(api_url, query = list("$limit" = 50000)) %>% 
  content("parsed")
  
```

```{r}
rest_inspections %>%  
  count(boro, grade) %>% 
  pivot_wider(
    names_from = grade,
    values_from = n
  )
```

```{r}
rest_inspections = 
  rest_inspections %>% 
  filter(grade %in% c("A", "B", "C"), boro != "0")
```


Lets look at pizza places
```{r}
rest_inspections %>% 
  mutate(dba = str_to_upper(dba)) %>% 
  filter(str_detect(dba, "PIZZ")) %>% 
  count(boro, grade) %>% 
  pivot_wider(
    names_from = grade,
    values_from = n
  )
```


```{r}
rest_inspections %>% 
  mutate(dba = str_to_upper(dba)) %>% 
  filter(str_detect(dba, "PIZZ")) %>% 
  mutate(
    boro = fct_infreq(boro),
    boro = str_replace(boro, "Brooklyn", "HipsterVille")
  ) %>% 
  ggplot(aes(x = boro)) +
  geom_bar() +
  facet_wrap(. ~grade)
```


## Napoleon Dynamite

Get some Napoleon Dynamite Amazon reviews

```{r}
nap_url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

napoleon_html = read_html(nap_url)

review_titles = 
  napoleon_html %>% 
  html_nodes(".a-text-bold span") %>% 
  html_text()

review_text = 
  napoleon_html %>% 
  html_nodes(".review-text-content span") %>% 
    html_text()

nap_df = 
  tibble(
    titles = review_titles,
    text = review_text
  )
```









